# Generated by Django 4.1.3 on 2022-12-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bay_number', models.IntegerField()),
                ('status', models.CharField(default='Free', max_length=100)),
            ],
        ),
    ]
